#!/bin/sh


flag_error=false;

for js in $(git diff-index --name-only  HEAD -- | grep '\.js$'); do

	err_log=`gjslint $js`
	errors=`echo $err_log | grep -c 'E:*:'`
    if [ $((errors)) -gt 0 ] ; then
    	echo "Some errors found in $js..."
    	echo "trying to autofix them..."
    	fixjsstyle $js  	
		err_log=`gjslint $js`;
		errors=`echo $err_log | grep -c 'E:*:'`
		if [ $((errors)) -gt 0 ] ; then
			flag_error=true;
			echo "Could not autofix..."
			echo
			echo "$err_log"
			echo
		else "$js successfully fixed"
		fi
    else
        echo "$js validated"
    fi  
done

if $flag_error; then
echo "files to be committed contain style errors"
	read -p "do you want to commit anyway? y/n " yno
	case $yno in

        [yY]* )
        		echo "committing"
                exit 0;
                break
                ;;

        [nN]* )
        		echo "aborting"
                exit 1
                break
                ;;
        *) echo "Invalid input"
            ;;
	esac
else
	echo "js files validated"
	exit 0;
fi
